/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MoveList {
    'moves': [];
  }
  interface MoveListAttributes extends StencilHTMLAttributes {
    'moves'?: [];
  }

  interface NumInput {
    'func': any;
    'no': number;
  }
  interface NumInputAttributes extends StencilHTMLAttributes {
    'func'?: any;
    'no'?: number;
  }

  interface PokemonSprite {
    'src': any;
  }
  interface PokemonSpriteAttributes extends StencilHTMLAttributes {
    'src'?: any;
  }

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface PokedexClass {}
  interface PokedexClassAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'MoveList': Components.MoveList;
    'NumInput': Components.NumInput;
    'PokemonSprite': Components.PokemonSprite;
    'MyComponent': Components.MyComponent;
    'PokedexClass': Components.PokedexClass;
  }

  interface StencilIntrinsicElements {
    'move-list': Components.MoveListAttributes;
    'num-input': Components.NumInputAttributes;
    'pokemon-sprite': Components.PokemonSpriteAttributes;
    'my-component': Components.MyComponentAttributes;
    'pokedex-class': Components.PokedexClassAttributes;
  }


  interface HTMLMoveListElement extends Components.MoveList, HTMLStencilElement {}
  var HTMLMoveListElement: {
    prototype: HTMLMoveListElement;
    new (): HTMLMoveListElement;
  };

  interface HTMLNumInputElement extends Components.NumInput, HTMLStencilElement {}
  var HTMLNumInputElement: {
    prototype: HTMLNumInputElement;
    new (): HTMLNumInputElement;
  };

  interface HTMLPokemonSpriteElement extends Components.PokemonSprite, HTMLStencilElement {}
  var HTMLPokemonSpriteElement: {
    prototype: HTMLPokemonSpriteElement;
    new (): HTMLPokemonSpriteElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLPokedexClassElement extends Components.PokedexClass, HTMLStencilElement {}
  var HTMLPokedexClassElement: {
    prototype: HTMLPokedexClassElement;
    new (): HTMLPokedexClassElement;
  };

  interface HTMLElementTagNameMap {
    'move-list': HTMLMoveListElement
    'num-input': HTMLNumInputElement
    'pokemon-sprite': HTMLPokemonSpriteElement
    'my-component': HTMLMyComponentElement
    'pokedex-class': HTMLPokedexClassElement
  }

  interface ElementTagNameMap {
    'move-list': HTMLMoveListElement;
    'num-input': HTMLNumInputElement;
    'pokemon-sprite': HTMLPokemonSpriteElement;
    'my-component': HTMLMyComponentElement;
    'pokedex-class': HTMLPokedexClassElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
